# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: major

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: ðŸ’¥ Breaking changes
    labels:
      - breaking
      - major
  - title: ðŸš€ New features and improvements
    labels:
      - minor
  - title: ðŸ› Bug fixes
    labels:
      - patch
  - title: ðŸ“ Documentation updates
    labels:
      - documentation
  - title: ðŸŒ Localization and translation
    labels:
      - localization
  - title: ðŸŒ Community-related changes
    labels:
      - community
  - title: ðŸ‘» Maintenance
    labels:
      - chore
      - maintenance
  - title: ðŸš¦ Tests
    labels:
      - test
  # - title: âœ Other changes
  # Default label used by Dependabot
  - title: ðŸ“¦ Dependency updates
    labels:
      - dependencies
    collapse-after: 15
exclude-labels:
  - skip-changelog
  - invalid
change-template: '- #$NUMBER: thanks @$AUTHOR - $TITLE Body-> $BODY URL-> $URL BASE_REF_NAME-> $BASE_REF_NAME HEAD_REF_NAME-> $HEAD_REF_NAME '
template: |
  <!-- Optional: add a release summary here -->
  $CHANGES

header: $CHANGES $CONTRIBUTORS $PREVIOUS_TAG $REPOSITORY $OWNER
footer: $CHANGES $CONTRIBUTORS $PREVIOUS_TAG $REPOSITORY $OWNER


autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'

  - label: 'major'
    branch:
      - '/major\/.+/'

  - label: 'minor'
    branch:
      - '/feature\/.+/'

  - label: 'patch'
    branch:
      - '/fix\/.+/'


name-template: '@reduxhooks/$RESOLVED_VERSION'
tag-template: '@reduxhooks/$RESOLVED_VERSION'