# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
      - major
  - title: 🚀 New features and improvements
    labels:
      - minor
  - title: 🐛 Bug fixes
    labels:
      - patch
  - title: 📝 Documentation updates
    labels:
      - documentation
  - title: 🌐 Localization and translation
    labels:
      - localization
  - title: 🌐 Community-related changes
    labels:
      - community
  - title: 👻 Maintenance
    labels:
      - chore
      - maintenance
  - title: 🚦 Tests
    labels:
      - test
  # - title: ✍ Other changes
  # Default label used by Dependabot
  - title: 📦 Dependency updates
    labels:
      - dependencies
    collapse-after: 15
exclude-labels:
  - skip-changelog
  - invalid

include-labels:
  - "major"
  - "minor"
  - "patch"
  - "breaking"
change-template: '- #$NUMBER $COMMIT thanks @$AUTHOR - $TITLE'
template: |
  <!-- Optional: add a release summary here -->
  $CHANGES

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'

  - label: 'major'
    branch:
      - '/major\/.+/'

  - label: 'minor'
    branch:
      - '/minor\/.+/'

  - label: 'patch'
    branch:
      - '/patch\/.+/'


name-template: '@reduxhooks/$RESOLVED_VERSION'
tag-template: '@reduxhooks/$RESOLVED_VERSION'