name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
    contents: write
    pull-requests: write

jobs:

  fetch_commit_id:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Check Current Directory
        run: |
          pwd
          ls -l
          cd ..
          cd runner
          ls -l

      - name: Get Commit Id
        run: |
          echo "Action Ran"
          echo "ACTION_STATE=yellow" >> $GITHUB_ENV

      - name: Preprocess Configuration
        run: |
          sed "s/\$NUMBER/\$NUMBER (\$ACTION_STATE)/g" ../../../release-drafter.yml > processed-release-drafter.yml

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: processed-release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
