name: Get Commit ID

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:

  fetch_commit_id:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Get Commit Id
        run: |
          echo "Action Ran"
          echo "action_state=yellow" >> $GITHUB_ENV
          echo "${{ env.action_state }} COMMIT ID"

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTION_STATE: this is text
