name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:

  fetch_commit_id:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
      - name: Get Commit Id
        run: |
          echo "Action Ran"
          echo "ACTION_STATE=yellow" >> $GITHUB_ENV

      - name: Modify Change Template
        run: sed -i "s/\$NUMBER/\$NUMBER (\$ACTION_STATE)/g" release-drafter.yml

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
