name: Release Workflow

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-22.04
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release Notes v1.0.0" \
              --generate-notes


# WORKING
# name: Release Workflow

# on:
#   push:
#     branches:
#       - master

# permissions:
#   contents: write

# jobs:
#   release:
#     name: Release pushed tag
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Create release
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}
#           tag: ${{ github.ref_name }}
#         run: |
#           gh release create "$tag" \
#               --repo="$GITHUB_REPOSITORY" \
#               --title="Release Notes v1.0.0" \
#               --generate-notes
