name: Release Notes

on:
  push:
    branches: [ master ]

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install
      - name: Install dependencies
        run: npm install conventional-changelog --save-dev

      - name: Generate release notes
        run: npx conventional-changelog -p angular -i CHANGELOG.md -u
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}