name: Release Workflow

on:
  push:
    branches:
      - master

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Changelog
        run: |
          # Generate changelog here
          echo "Changelog generated."

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version-packages
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v1.0.0
          release_name: Release 1.0.0
          body: |
            Changelog: 
            ${{ steps.generate_changelog.outputs.changelog }}
          draft: false
          prerelease: false

      # - name: Publish Release
      #   if: steps.create_release.outputs.release_created == 'true'
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PAT }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./path/to/release-asset.zip
      #     asset_name: release-asset.zip
      #     asset_content_type: application/zip
