name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
  # pull_request event is required only for autolabeler
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]
  # pull_request_target event is required for autolabeler to support PRs from forks
  # pull_request_target:
  #   types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Fetch commit ID
      - name: Get commit ID
        id: commit
        run: |
         echo "action_state=yellow" >> "$GITHUB_ENV"
         echo "::set-env name=COMMIT_ID::$(git log --format='%H' -n 1)"

      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_ID: ${{ steps.commit.outputs.COMMIT_ID }}