name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Generate Changelog
        id: generate_changelog
        run: |
          # Replace with your preferred changelog generation script
          # (e.g., custom script, `github-script-action/script`)
          echo "Changelog generated based on commit messages and labels (replace with your logic)."

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.sha }}  # Use dynamic tag based on commit SHA
          release_name: "Release ${{ github.sha }}"  # Dynamic release name
          body: |
            **Changelog:**

            ${{ steps.generate_changelog.outputs.changelog }}

            # Consider adding more release notes details
            # (e.g., links to issues, tested platforms)

          draft: false  # Publish release automatically
          prerelease: false  # Indicate a stable release

      # Optional steps:
      # - Upload artifacts (e.g., built products)
      # - Send release notifications to external services

