name: Release Notes

on:
  push:
    branches: [ master ]

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install conventional-changelog --save-dev
      - name: Generate release notes
        run: npx conventional-changelog -p angular -i CHANGELOG.md -u
