name: Release Workflow

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get Previous Commit SHA
        id: get_previous_commit
        run: |
          if [ "$(git rev-parse HEAD^ 2>/dev/null)" ]; then
            previous_commit=$(git rev-parse HEAD^)
            echo "::set-output name=previous_commit::$previous_commit"
          else
            echo "::set-output name=previous_commit::"
          fi

      - name: Generate Release Notes
        id: generate_release_notes
        run: |
          if [ -n "${{ steps.get_previous_commit.outputs.previous_commit }}" ]; then
            release_notes=$(git log --pretty=format:"- %s" ${{ steps.get_previous_commit.outputs.previous_commit }}..HEAD)
            echo "Release Notes: $release_notes"
            echo "::set-output name=release_notes::$release_notes"
          else
            echo "::set-output name=release_notes::No previous commit found."
          fi

      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: v1.0.0
          release_name: Release 1.0.0
          body: |
            Changeloged:
            ${{ steps.generate_release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
