name: Release

on:
  push:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install Node verions 20 
      - name: Set up Node.js 20.8.1
        uses: actions/setup-node@v3
        with:
          node-version: '20.8.1'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run semantic-release
      - name: Run semantic-release
        run: npx semantic-release --repository-url https://github.com/syed-orgn/redux-hooks
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}




# WORKING 3
# on:
#   push:
#     tags:
#       - 'v*'

# name: Create Release

# jobs:

#   create-github-release:
#     name: Create GitHub Release
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: Create Release
#         run: gh release create ${{ github.ref }} --generate-notes
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}





# WORKING 2
# name: Release Workflow

# on:
#   push:
#     tags:
#       - 'v*'

# jobs:
#   release:
#     name: Release pushed tag
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#       - name: Create release
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}
#           tag: ${{ github.ref_name }}
#         run: |
#           gh release create "$tag" \
#               --title="Release Notes v1.0.0" \
#               --generate-notes



# WORKING 1
# name: Release Workflow

# on:
#   push:
#     branches:
#       - master

# permissions:
#   contents: write

# jobs:
#   release:
#     name: Release pushed tag
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Create release
#         env:
#           GITHUB_TOKEN: ${{ secrets.PAT }}
#           tag: ${{ github.ref_name }}
#         run: |
#           gh release create "$tag" \
#               --repo="$GITHUB_REPOSITORY" \
#               --title="Release Notes v1.0.0" \
#               --generate-notes
