name: Send Email on Push

on:
  push:
    branches:
      - master

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v2
        
      - name: Debug Contents of Directory
        run: | 
          echo Contents of directory: $(ls -R ../../src/send-email/attachments/htmlfiles)
          echo Contents of directory2: ${ls -R ../../src/send-email/attachments/htmlfiles}

      - name: Send Email with Attachment
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: New code pushed to repository
          body: Code has been pushed to the repository.
          to: zaidi.yam5@gmail.com
          from: Syed Abbas Muttaqi - CEDCOSS
          attachments: |
            ../../src/send-email/attachments/htmlfiles/home.html
