name: Send Email on Push

on:
  push:
    branches:
      - master

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: New code pushed to repository
          body: Code has been pushed to the repository.
          to: zaidi.yam5@gmail.com
          from: Abbas Muttaqi - CEDCOSS
          attachments: |
            src/send-email/attachements/htmlfiles/home.html
          # options: "--insecure" # This is necessary if using Gmail
